#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__

#define NUM_THREADS 5
#define COURSE_PREFIX "[COURSE:1][ASSIGNMENT:5]"
#define EVEN_THREAD_CORE 2
#define ODD_THREAD_CORE 3
#define SEQUENCER_CORE 1
#define MY_CLOCK_TYPE CLOCK_MONOTONIC_RAW
#define BASE_PERIOD_NS 10000000ULL // 10 ms

#endif /* !__APP_CONFIG_H__
#define __APP_CONFIG_H__ */
